title = "Adebali Lab"
baseURL = "/"
languageCode = "en-us"
theme = "gohugo-theme-ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-126243765-1"
enableRobotsTXT = true


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Where genomes are deciphered."
  facebook = ""
  email = "oadebali@sabanciuniv.edu"
  address = "Orta Mahallesi, Sabancı Ünv. No:27, FENS, 34956 Tuzla/İstanbul, Turkey"
  twitter = "https://twitter.com/compGenomics"
  instagram = ""
  youtube = ""
  github = ""
  linkedin = ""
  institution = "Sabanci University"
  longtitude= "40.890408"
  latitude= "29.379349"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2
  recent_publication_number = 5
  recent_news_number = 3
  mainSections = ["news"]
  custom_css = ["css/person.css"]
  # noInMenu = "Posts"

# [[menu.main]]
#    name = "a"
#    url  = "/"
#    weight = 0
